planning_plugins:
  - ompl_interface/OMPLPlanner
planning_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints

planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0  # Max motion length
  RRTstar:
    type: geometric::RRTstar
    range: 0.0

panda_left:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar

panda_right:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar

dual_arms:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar